version: 2.1

orbs:
  android: circleci/android@1.0.3

references:

  workspace: &workspace
               ~/code

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      TERM: dumb
      _JAVA_OPTIONS: -Xmx1536m
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -Dkotlin.compiler.execution.strategy=in-process
    resource_class: large

  gradle_key: &gradle_key
                jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  gems_key: &gems_key
              gems-{{ checksum "Gemfile.lock" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  restore_gems_cache: &restore_gems_cache
    restore_cache:
      key: *gems_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      paths:
        - ~/.gradle
        - ~/.m2
      key: *gradle_key

  save_gems_cache: &save_gems_cache
    save_cache:
      paths:
        - vendor/bundle
      key: *gems_key

  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: |
        gem install bundler
        bundle check || bundle update || bundle install --path vendor/bundl

jobs:

  test_distribution:
    <<: *android_config
    steps:

      - checkout
      - android/install-ndk:
          ndk-version: android-ndk-r21
          ndk-sha: afc9c0b9faad222898ac8168c78ad4ccac8a1b5c
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - run:
          name: Init permission
          command: sudo chmod +x gradlew
      - run:
          name: Upload APK to Drive & notify to slack test_bot channel
          no_output_timeout: 30m
          command: bundle exec fastlane testDistribution

  distribution:
    <<: *android_config
    steps:
      - checkout
      - android/install-ndk:
          ndk-version: android-ndk-r21
          ndk-sha: afc9c0b9faad222898ac8168c78ad4ccac8a1b5c
      - *restore_gradle_cache
      - *restore_gems_cache
      - *ruby_dependencies
      - *save_gradle_cache
      - *save_gems_cache
      - run:
          name: Init permission
          command: sudo chmod +x gradlew
      - run:
          name: Upload APK to Drive, Firebase Distribution & notify to slack KLive channel
          no_output_timeout: 30m
          command: bundle exec fastlane distribution


workflows:
  version: 2
  workflow:

    jobs:
      - test_distribution:
          filters:
            branches:
              only:
                - feat-ci
      - distribution:
          filters:
            branches:
              only:
                - /release-.*/
                - /hotfix\/release-.*/