version: 2.1

orbs:
  android: circleci/android@0.2.1
  slack: circleci/slack@4.8.3
references:
  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: |
        gem install bundler
        bundle check || bundle update || bundle install --path vendor/bundl
  gradle_key: &gradle_key
                jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  gems_key: &gems_key
              gems-{{ checksum "Gemfile.lock" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

    restore_gems_cache: &restore_gems_cache
      restore_cache:
        key: *gems_key

    save_gradle_cache: &save_gradle_cache
      save_cache:
        paths:
          - ~/.gradle
          - ~/.m2
        key: *gradle_key

    save_gems_cache: &save_gems_cache
      save_cache:
        paths:
          - vendor/bundle
        key: *gems_key
config_android: &config_android
  working_directory: ~/code
  docker:
    - image: circleci/android:api-30

  environment:
    JVM_OPTS: -Xmx3200m

build_test: &build_test
  <<: *config_android
  steps:
    - checkout
    - restore_cache:
        <<: *cache_key
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - save_cache:
        <<: *cache_key
        paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper

    - run:
        name: Build app
        command: ./gradlew build

deploy_debug_to_firebase: &deploy_debug_to_firebase
  <<: *config_android
  steps:
    - checkout
    - *ruby_dependencies
    - *restore_gems_cache
    - *save_gems_cache

    - run:
        name: Build debug
        command: ./gradlew :app:assembleDebug

    - run:
        name: Install Firebase CLI
        command: |
          curl -sL https://firebase.tools | bash
    - run:
        name: Init permission
        command: sudo chmod +x gradlew

    - run:
        name: Upload File APK Debug to Firebase App Distribution
        command: firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --app $FIREBASE_APP_ID --token $FIREBASE_TOKEN_CLI --release-notes "Upload APK to Firebase"

    - slack/notify:
        custom: |
          {
            "blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "Hello, Assistant to the Regional Manager Dwight! *Michael Scott* wants to know where you'd like to take the Paper Company investors to dinner tonight.\n\n *Please select a restaurant:*"
            			}
            		},
            		{
            			"type": "divider"
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "*Farmhouse Thai Cuisine*\n:star::star::star::star: 1528 reviews\n They do have some vegan options, like the roti and curry, plus they have a ton of salad stuff and noodles can be ordered without meat!! They have something for everyone here"
            			},
            			"accessory": {
            				"type": "image",
            				"image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/c7ed05m9lC2EmA3Aruue7A/o.jpg",
            				"alt_text": "alt text for image"
            			}
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "*Kin Khao*\n:star::star::star::star: 1638 reviews\n The sticky rice also goes wonderfully with the caramelized pork belly, which is absolutely melt-in-your-mouth and so soft."
            			},
            			"accessory": {
            				"type": "image",
            				"image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/korel-1YjNtFtJlMTaC26A/o.jpg",
            				"alt_text": "alt text for image"
            			}
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": "*Ler Ros*\n:star::star::star::star: 2082 reviews\n I would really recommend the  Yum Koh Moo Yang - Spicy lime dressing and roasted quick marinated pork shoulder, basil leaves, chili & rice powder."
            			},
            			"accessory": {
            				"type": "image",
            				"image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/DawwNigKJ2ckPeDeDM7jAg/o.jpg",
            				"alt_text": "alt text for image"
            			}
            		},
            		{
            			"type": "divider"
            		},
            		{
            			"type": "actions",
            			"elements": [
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"text": "Farmhouse",
            						"emoji": true
            					},
            					"value": "click_me_123"
            				},
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"text": "Kin Khao",
            						"emoji": true
            					},
            					"value": "click_me_123",
            					"url": "https://google.com"
            				},
            				{
            					"type": "button",
            					"text": {
            						"type": "plain_text",
            						"text": "Ler Ros",
            						"emoji": true
            					},
            					"value": "click_me_123",
            					"url": "https://google.com"
            				}
            			]
            		}
            	]
          }
        event: always
jobs:

  deploy_debug_to_firebase:
    <<: *deploy_debug_to_firebase

workflows:
  version: 1
  build_test_and_deploy:
    jobs:
      - deploy_debug_to_firebase:
          filters:
            branches:
              only: circleci-project-setup