version: 2.1

orbs:
  android: circleci/android@0.2.1
  slack: circleci/slack@4.1
references:
  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: |
        gem install bundler
        bundle check || bundle update || bundle install --path vendor/bundl
  gradle_key: &gradle_key
                jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  gems_key: &gems_key
              gems-{{ checksum "Gemfile.lock" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

    restore_gems_cache: &restore_gems_cache
      restore_cache:
        key: *gems_key

    save_gradle_cache: &save_gradle_cache
      save_cache:
        paths:
          - ~/.gradle
          - ~/.m2
        key: *gradle_key

    save_gems_cache: &save_gems_cache
      save_cache:
        paths:
          - vendor/bundle
        key: *gems_key
config_android: &config_android
  working_directory: ~/code
  docker:
    - image: circleci/android:api-30

  environment:
    JVM_OPTS: -Xmx3200m

build_test: &build_test
  <<: *config_android
  steps:
    - checkout
    - restore_cache:
        <<: *cache_key
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies

    - save_cache:
        <<: *cache_key
        paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper

    - run:
        name: Build app
        command: ./gradlew build

deploy_debug_to_firebase: &deploy_debug_to_firebase
  <<: *config_android
  steps:
    - checkout
    - *ruby_dependencies
    - *restore_gems_cache
    - *save_gems_cache
    - run:
        name: Build debug
        command: ./gradlew :app:assembleDebug

    - run:
        name: Install Firebase CLI
        command: |
          curl -sL https://firebase.tools | bash
    - run:
        name: Init permission
        command: sudo chmod +x gradlew
    - run:
        name: Upload File APK Debug to Firebase App Distribution
        command: bundle exec fastlane distribute

jobs:

  deploy_debug_to_firebase:
    <<: *deploy_debug_to_firebase

workflows:
  version: 1
  build_test_and_deploy:
    jobs:
      - deploy_debug_to_firebase:
          filters:
            branches:
              only: circleci-project-setup